### ISSUE TITLE
Enabling_23 - tu_01_09_17_05 - Crossword Template

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#306]
SNS Task 17 Step 5
1) bold, italics not working in Crossword Clues 
2) wrapped text is being covered by scroll bar in Crossword Clues display: words on the right cannot be properly read

**Comment by sdub** [comment]
2) wrapped text is being covered by scroll bar in Crossword Clues display: words on the right cannot be properly read
This is happening AGAIN in Malay (Task 6 Step 7)  over a YEAR after requesting a fix. When issues like these are fixed in a product, all future iterations of a template should include the fix!!!
![en23_crossword_ml_sns_t6s7](https://cloud.githubusercontent.com/assets/7586260/11693770/9a2bb026-9e5b-11e5-8648-3a99a3de181e.JPG)

**Comment by proti9** [comment]
At the moment, updating this issue applied to all current and future languages. After closing it, there is no change on this template. 

As shown in the below, in my side, it shows properly on Malay in staging. I also tried to look at in a testing machine to test a common user environment for other languages which are already on the live site. It give the same result.

![ml_01_03_06_07_enabling_23_151209](https://cloud.githubusercontent.com/assets/7441476/11695776/d2752d36-9e65-11e5-899a-aa9aa018b09f.jpg)

**Comment by sdub** [comment]
Thank you! Closing for now.
