### ISSUE TITLE
Enabling_05 - jn_01_06_12_05 - No scrollbars showing

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#308]
Longer TL entries flow over text box, please add scroll bar (again).

![en5---missingscroll](https://cloud.githubusercontent.com/assets/7586260/5687338/6ac01172-9800-11e4-9539-448e9b3a713d.png)

**Comment by proti9** [comment]
It is updated in the staging. Please check it again.

**Comment by sdub** [comment]
Looks good! Thank you.
