### ISSUE TITLE
Enabling_09 - jn_01_04_07_04 - "Set" button/counter display issue

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#309]
In Indonesian Task 7, Step 4, EN 9 there is a display issue with the set counter in the lower right corner. In all three sets it becomes pixelated after an answer is selected. This happens with both correct and incorrect answers.  Multiple coordinators have reported this issue, in only this template, being visible in Firefox. However, the issue is not visible 100% of the time.
![en9-button](https://cloud.githubusercontent.com/assets/7586260/5779641/56fdb474-9d59-11e4-9f15-6d95f9fc5f78.png)

**Comment by proti9** [comment]
It is updated. Please try again.

**Comment by sdub** [comment]
Seems to be working well, thank you.
