### ISSUE TITLE
Capstone_01 - hj_01_09_17_05 - SnS Capstone1 Template not displaying content

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#311]
Please see Task 17 Step 5

**Comment by proti9** [comment]
Here is the screenshot for hj_01_09_17_05 showing contents.

![hj_01_09_17_05_150402_b](https://cloud.githubusercontent.com/assets/7441476/6967365/a85b0984-d913-11e4-9fd3-f41067506af2.jpg)

If you still have an issue, let me know.

**Comment by sdub** [comment]
Issue persists.
