### ISSUE TITLE
WarmUp_07a - hj_01_01_01_02 - WarmUp 7a - TL and English alignment update needed

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#312]
WarmUp 7a - e.g. Hindi SnS Task 1, Step 2

TL and English should be aligned underneath each other as the TL for Hindi (and Japanese) is written LTR (see examples "donkey" and ""rabbit" below)
 
![wu7a_capture](https://cloud.githubusercontent.com/assets/7586260/6581223/c7713266-c712-11e4-90a3-6227d8ef6250.jpg)

**Comment by proti9** [comment]
It is updated by applying the new UI. Please check it again.

**Comment by sdub** [comment]
Two issues in new template:
-Text alignment (see screen shot below)
-Selected letter should be showing in orange in word as in Hindi sample words above --currently the font in sample words is all black
![7a_alignment](https://cloud.githubusercontent.com/assets/7586260/7091664/46847fa8-df60-11e4-9987-4fbebc83453d.jpg)

**Comment by proti9** [comment]
Step 4 uses WarmUp_08a. The template is updated. You can also use images for examples. Please try it again.

**Comment by sdub** [comment]
WU7a  Looks good for now! WU8a needs to be updated instead

**Comment by proti9** [comment]
It is updated for WarmUp_08a. Please check it again.

**Comment by sdub** [comment]
Done, thank you!
