### ISSUE TITLE
WarmUp_07a - hj_01_01_01_02 - Warm-Up 7a - Hindi Task 1 Step 2

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#313]
-Hindi words should be next to the play buttons . Currently English translations are next to the play buttons.
-Certain Hindi vowels are not displayed correctly. They are being displayed in their dependent forms not connected to other letters.
-If there is only one sample word, there should be only one play button.
-Hindi font should be larger
-All elements should be aligned on page - need UI design
-White box on gray window extends past box on bottom

**Comment by sdub** [comment]
Redesigned layout attached
_Please use blue instead of red font to mark the letters within the sample words.

![warm-up_7a_v1_big_feedback](https://cloud.githubusercontent.com/assets/7586260/6710625/3e22e7ec-cd3f-11e4-8ca9-095880049ef0.png)

**Comment by proti9** [comment]
It is updated as you know. And the current xml generator accepts two sameple examples for WarmUp_07. I hope there would be two. In case you really want to use one example for Hindi. I will check xml file to show it when the contents is finalized. Let me know. And, this issue would be considers for future languages.

**Comment by sdub** [comment]
Looks good for now!
