### ISSUE TITLE
Enabling_51 - hj_01_01_01_05 - EN51 - Hindi Task 1, Step 5

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#315]
-The Hindi characters are not connected to each other in both instances of the written script of the screen. 
-The characters in the example word and fill in the blank word are not displayed similarly. Some marks or diacritics are missing.
-Some vowels are not being automatically "linked" to the consonants.
-Skinny tiny places are left for vowels. (capture - font issue 2)
-The bottom scroll bar is not necessary. (PC Firefox)
-alignment of English translation is off, move to left to be in line with Hindi above
-All elements should be aligned on page - need UI design

**Comment by proti9** [comment]
It is updated in the staging.

**Comment by sdub** [comment]
Looks good so far, thank you!
