### ISSUE TITLE
DragDrop - hj_01_01_02_02 - Drag Drop - Hindi Task 2, Step 2 

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#317]
-The sounds should play only when the play button is clicked. There should be no sound when dragging/dropping/placing an entry on the map/image.
-Letters are not being connected in the Hindi font, neither on the menu on the left, nor on the map.
-Hindi font should be a bit larger, also when dropped in place
-Hint and FB text could be a bit smaller to minimize scrolling

**Comment by sdub** [comment]
Looking good, thank you!

**Comment by sdub** [comment]
I am sorry to have to re-open this one, but I missed the FB font being tiny now.
Please make it the same size as in most of the other SnS Templates. One or two point sizes larger than now should do the trick.

**Comment by sueykim** [comment]
I made 2 point larger. Please take a look.

**Comment by sdub** [comment]
Good to go, thank you!
