### ISSUE TITLE
Enabling_05 - hj_01_01_01_06 - Enabling 5 -  Hindi SNS Task 1, Step 6 - Hindi font not connecting

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#319]
Hindi font not connecting, likely another spacing issue

**Comment by sueykim** [comment]
It's been fixed. css letter-spacing

**Comment by sdub** [comment]
Font is connecting but is very small, could we please enlarge by 3 or so point sizes please?

**Comment by proti9** [comment]
Please check it again.

**Comment by sdub** [comment]
Looking good now, thank you!
