### ISSUE TITLE
Enabling_22 - hj_01_07_13_05 - Enabling 22 - Hindi  - can't complete some blanks (T13, S5)

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#320]
Enabling 22 blocks drag-drop of items into blank at end of line:
Look at "geeta" (woman doctor, set 2); (additional example)  "neha" (old woman, set 4)

![hj_enabling22](https://cloud.githubusercontent.com/assets/7586260/6710851/9c6c3294-cd40-11e4-902e-400d995d54bb.JPG)

**Comment by proti9** [comment]
It is updated. Please check it again.

**Comment by sdub** [comment]
Good to go! thanks.
