### ISSUE TITLE
Hindi Mil - Fix letter spacing in template, English and Hindi

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#322]
Hindi and English words in Military templates are still being spread apart, fix was found in the programming meeting

**Comment by sdub** [comment]
It looks like the font family (and size) changed...Could we keep the same font please and just fix the spacing?

**Comment by proti9** [comment]
Please try each step for Military again. And, let us know by steps.

**Comment by sdub** [comment]
The Font in Mil Step 6 is the one used in the framework as well (e.g. directions), The font in the other Mil Steps is not the same.

**Comment by sdub** [comment]
Good to go! thanks.
