### ISSUE TITLE
EN 12 - ex. Task 6 Step 4 - Hindi font not connecting

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#325]

**Comment by sdub** [comment]
Also need the Hindi font a few sizes larger.

**Comment by sueykim** [comment]
Fixed and updated on Github.

**Comment by sdub** [comment]
Font still too small, please update. Thank you!

**Comment by sdub** [comment]
Now font is so large that the tops of the letters are shaved off and not visible. Could we find a happy medium? Please make the font two points larger than it was originally.

**Comment by sdub** [comment]
It looks great now, thank you!
