### ISSUE TITLE
Enabling_10 - hj_01_06_11_03 - EN10 - ex. Task 11 Step 3 - Hindi font not connecting and too small

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#330]

**Comment by proti9** [comment]
It is updated. Please try it again.

**Comment by sdub** [comment]
Looks good in the drop-down menus for items 1-4, but the drop down for the last item on a page is still showing in small font (but it is connecting)... Could you please check?
![t11s3](https://cloud.githubusercontent.com/assets/7586260/7092173/65d76308-df64-11e4-9521-c763adb7e8fa.jpg)

**Comment by proti9** [comment]
It is updated. Please try it again.

**Comment by sdub** [comment]
Good to go, thank you.
