### ISSUE TITLE
Enabling_04 - hj_01_07_14_02 - EN4 - ex. T 14, S2 - unnecessary scroll bars

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#331]
In the Enabling 4 template, unnecessary scroll bars sometimes appear in the feedback. 
 
Examples:
hj_01_07_14_02 (SnS Task 14, Step 2), items 3 (dry), 7 (sunny), 9 (cold), 11 (clear), 15 (storm)

hj_01_10_19_01 (SnS Task 19, Step 1), items 1 (water), 3 (apple), 6 (grapes), 7 (lamb), 8 (pork), 9 (chicken), 12 (eggs), 13 (bread), 16 (tea)

**Comment by sdub** [comment]
The scroll bar issue is fixed,. However This is now, oddly, replacing all images with one single picture when using the arrow function to move through the wheel (I am looking on Firefox. )

Could you check again please?

![en4_imageissue](https://cloud.githubusercontent.com/assets/7586260/6966609/340fc406-d90f-11e4-955a-b090dabe3fc2.jpg)

**Comment by proti9** [comment]
Here is the screenshot for hj_01_07_14_02 showing different pictures on Firefox.

![hj_01_07_14_02_150402_b](https://cloud.githubusercontent.com/assets/7441476/6967463/55c39046-d914-11e4-8808-7a14767f27b9.jpg)

In case, please clear all history, and try it again. If you still have an issue, let me know.

**Comment by sdub** [comment]
Perhaps I was not clear. The pictures are only the same WHILE THE MOVEMENT OF THE WHEEL takes place. Afterward, they are all different. Please check again,

**Comment by proti9** [comment]
I should see your system to look at the issue. I will be there.

**Comment by sdub** [comment]
Same display issue continues on my computer and also for a few of the HS Coordinators. No issues on other computers. No difference if Mac or PC. The mystery continues.
