### ISSUE TITLE
DragDrop - hj_01_01_02_02 - DragDrop temaplte - Task 2, Step 2, Incorrect button sometimes being replaced

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#332]
The incorrect button in a hint box sometimes being replaced (ca. 10 percent of the time) with a none-working audio button and other visual remnents, screenshot below
![hj_t2s2_incorrectbutton](https://cloud.githubusercontent.com/assets/7586260/7029553/44af9d92-dd13-11e4-8d17-8476e51f044d.jpg)

**Comment by proti9** [comment]
Please try again.

**Comment by sdub** [comment]
Cleared cache and local storage, still occurring....

**Comment by sdub** [comment]
Not occurring lately and not at all for others, so closing issue
