### ISSUE TITLE
Enabling_12 - hj_01_01_02_05 - EN 12 - Task 2 Step 5 - MP4 slots blank until audio button clicked

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#334]
MP4 slots are blank until the audio button clicked to play them, should be showing the still images upon entry to theset

**Comment by proti9** [comment]
It is showing. Please try again.

**Comment by sdub** [comment]
Problem persists,, please check again. : (

**Comment by proti9** [comment]
Having ogv files would resolve this issue on Firefox. Pease check it again.

**Comment by sdub** [comment]
OGvs took care of this...Good to know! Thank you.
