### ISSUE TITLE
Enabling_20 - hj_01_02_04_06 - Message Board - Hindi Task 4 , Step 6

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#336]
Template should be showing a specific note in large upon entering the activity, Each new question should prompt one of the notes to come to the forefront automatically. The student should not have to select as is currently apparently the case.
(Working example in MSA HS, Task 9 Step 6)

**Comment by proti9** [comment]
The xml generator side is updated. Please re-publish the task having this activity, and try it again.

**Comment by sdub** [comment]
Works well, thank you!
