### ISSUE TITLE
Enabling_02 - hj_01_02_03_02 -  EN 2 - T3 S2, Hindi font not connecting

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#337]
Please disregard green button in screenshot - issue is the Hindi TL font, which is not connecting properly
![hj_t3s2_completedstep](https://cloud.githubusercontent.com/assets/7586260/7035373/a7244f76-dd3c-11e4-9be5-309b17ed456c.jpg)

**Comment by proti9** [comment]
It is updated. Please check it again.

**Comment by sdub** [comment]
looks OK now, thank you!
