### ISSUE TITLE
WarmUp_08a - hj_01_01_01_04 - WU 8a - T1 S4 - need larger font on Hindi letter

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#341]
Please enlarge Hindi letter sample in gray left bottom box to 128 px

**Comment by proti9** [comment]
Please check it again.

**Comment by sdub** [comment]
Issue with Hindi overlap in font box 
![wu7a_fontglitch](https://cloud.githubusercontent.com/assets/7586260/7278869/efefa2d2-e8cc-11e4-8a1c-5cbacf9e6f63.png)

**Comment by sdub** [comment]
This is for WU 8a, not 7a. Changing title back.

**Comment by proti9** [comment]
It is updated. Please try it again.

**Comment by sdub** [comment]
Looks good, thank you!
