### ISSUE TITLE
WarmUp_07a - hj_01_01_01_02 - WU 8a - T1 S2 extraneous scrolll bar in the letter feedback box

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#342]
The scroll bar in the letter description box appears even when it i unnecessary and there is no further content to scroll through. Also, line spacing of the last two lines of a  longer description is larger than in rest of description content. Scrolling might be eliminated if there lines spaces were properly adjusted?
![8a_scroller](https://cloud.githubusercontent.com/assets/7586260/7078197/c434847e-decb-11e4-9b1b-3866a001f7f3.jpg)

**Comment by proti9** [comment]
It is updated. Please try it again.

**Comment by sdub** [comment]
The larger box should take care of this. Thanks
