### ISSUE TITLE
WarmUp_08a - hj_01_01_01_04 - WU8 - T1 S2 -  Hindi highlight font color

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#343]
Empty space appearing where not needed - Generator input seems clean
![t1s2-fontglitch](https://cloud.githubusercontent.com/assets/7586260/7078388/6a43db20-decd-11e4-9fb9-1c9bfb7cae80.PNG)

**Comment by proti9** [comment]
It is updated as you know. Please check it again.

**Comment by sdub** [comment]
Will make images for WU7a this afternoon.

**Comment by sdub** [comment]
WU7a - highlighted letters should show in orange (as in WU 8 Step 2), not in red
![wu7a_fontglitch](https://cloud.githubusercontent.com/assets/7586260/7278894/184a575e-e8cd-11e4-80b6-0b5f0e4f62f4.png)

**Comment by proti9** [comment]
It would be the case on WarmUp_08a and be updated..

**Comment by sdub** [comment]
Looks good today, I will close this one.
Thank you!
