### ISSUE TITLE
Capstone_02 - hj_01_02_04_04 - SnS Capstone 2, T4S4, FB font too small

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#352]
FB font is teensy-weensy in this template, please adjust to match other templates in this task

**Comment by proti9** [comment]
It is adjusted. Please check it again.

**Comment by sdub** [comment]
Good size - but bottom loops of letters are being cut off now.

![cs2--44](https://cloud.githubusercontent.com/assets/7586260/7187234/11809db4-e424-11e4-8504-ac99f90356b7.jpg)

**Comment by proti9** [comment]
It is updated. Please try it again.

**Comment by sdub** [comment]
Much better, thank you!
