### ISSUE TITLE
Enabling_32 - hj_01_03_05_02 - LetterScramble - hj_01_03_05_03 - FB font too small

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#355]
Just a font asize or two should do the trick here
![t5_letterscramblefb](https://cloud.githubusercontent.com/assets/7586260/7120429/fc0c4f00-e1c1-11e4-87f9-a66ae1d14cbd.jpg)

**Comment by proti9** [comment]
It is updated. Please check it again.

**Comment by sdub** [comment]
Looks good, thanks!
