### ISSUE TITLE
Enabling_68- hj_01_05_09_04 - Hindi font cut off

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#360]
Letter loops below Hindi words being cut off

![en68noloops](https://cloud.githubusercontent.com/assets/7586260/7126832/a617c964-e1f1-11e4-9e31-cca2f6783b3d.jpg)

**Comment by proti9** [comment]
It is updated. Please check it again.

**Comment by sdub** [comment]
Looks good, thanks!
