### ISSUE TITLE
Enabling_07 - hj_01_04_07_06 - Hindi font issue

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#362]
Hindi font: bottom loops running into top loops of next line

![t7s6_fontissue](https://cloud.githubusercontent.com/assets/7586260/7187426/387470f2-e425-11e4-8c70-02a3e991e332.jpg)

**Comment by botrosyoussef** [comment]
fixed on staging.

**Comment by sdub** [comment]
Looking good, thank you!
