### ISSUE TITLE
Enabling_09 - hj_01_06_12_04 - Hindi font issues

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#363]
- Bottom of Hindi letters cutting off
- Bottom loops of Hindi font "running into" top loops of writing on line below

![t12s4_fontissue](https://cloud.githubusercontent.com/assets/7586260/7187466/732adcf4-e425-11e4-8add-175826747bd6.jpg)

**Comment by botrosyoussef** [comment]
fixed in staging.

**Comment by sdub** [comment]
The scroll bar on each entry is less than ideal now...Could we see what it looks like with the Hindi font being one point smaller, please?

**Comment by botrosyoussef** [comment]
fixed in staging, please check.

**Comment by sdub** [comment]
Looks great, thank you!
