### ISSUE TITLE
Capstone_02 - hj_01_07_13_03 - Hindi font issues, MP4 not showing

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#364]
-Hindi font not connecting tin the prompt text box
-MP4 not showing as image until play button pressed

![t13s3_fontsandmp4](https://cloud.githubusercontent.com/assets/7586260/7205854/20893a24-e4e1-11e4-9b1a-aa1ee7f5d49d.jpg)

**Comment by proti9** [comment]
It is updated for the character connecting issue at this moment. Please check it again.

**Comment by sdub** [comment]
OGVs took care of the media display issue, font  issue fixed as well.

Good to go!
