### ISSUE TITLE
Enabling_32 - hj_01_03_05_02 - LetterScramble - Hindi font in FB cut off

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#365]
![t5s2_fbfontissue](https://cloud.githubusercontent.com/assets/7586260/7211261/0dde3802-e50e-11e4-8d26-7e10bb109025.jpg)
Hindi font bottoms cut off

**Comment by proti9** [comment]
It is updated. Please check it again.

**Comment by sdub** [comment]
Looks good, thank you!
