### ISSUE TITLE
Enabling_20 - hj_01_02_04_06 - Hints disappearing too quickly

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#366]
Hints disappear even if user does NOT click OK button. Reviewer comments that box is disappearing too quickly to properly read and comprehend the content.

**Comment by proti9** [comment]
As you can see from the directions, when the mouse pointer hovers sticky note items, it shows typed texts for handwritten texts on the feedback area. Without moving a mouse to read and comprehand the content, it would not happen.

**Comment by sdub** [comment]
The hint is disappearing after 5 seconds without mousing over the note.... Please make this time longer, let's try 10 seconds.

**Comment by proti9** [comment]
It is applied. Please check it again.

**Comment by sdub** [comment]
Looks good, thank you!
