### ISSUE TITLE
Capstone_02 - hj_01_07_13_03 - Hindi font cut off only when FB one line

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#367]
Step 3, Capstone 2, in feedback, Hindi font is cut off at bottom when fb is one line only (#11 "old", #12 "mustache") - displays fine when FB has two lines or more.
![t13s3_fontfb](https://cloud.githubusercontent.com/assets/7586260/7286614/2102a77c-e902-11e4-95dd-03e908e06eb7.png)

**Comment by proti9** [comment]
It is updated. Please check it again.

**Comment by sdub** [comment]
Looks good now, thank you!
