### ISSUE TITLE
Enabling_02 - hj_01_08_15_03 - EN 2 - FB font too small

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#368]
Hello please adjust FB/hint font in EN2 to match more closely with other temapltes, perhaps a size or two larger
![en2_fbsize](https://cloud.githubusercontent.com/assets/7586260/7322993/70b7fd3a-ea60-11e4-8b97-51a75fea23d5.png)

**Comment by proti9** [comment]
It is updated. Please check it again.

**Comment by sdub** [comment]
Maaaaybeeee just a little bigger please....

**Comment by proti9** [comment]
It would show bigger now. Please check it again.

**Comment by sdub** [comment]
Looks good, thank you!
