### ISSUE TITLE
WarmUp_08a - hj_01_01_01_04 - WU 8a - T1 S4 - alignment

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#369]
The gray box should be bigger so that there is no scroll bar in the introduction and the top should be aligned with the top of the sample text.

![wu8a_alignment](https://cloud.githubusercontent.com/assets/7586260/7329066/4982837c-ea90-11e4-9447-0046383fe991.png)

**Comment by proti9** [comment]
It is updated. Please check it again.

**Comment by sdub** [comment]
Looks great, thank you!
