### ISSUE TITLE
Enabling_02 - ja_01_09_18_03 - Japanese - Enabling 2 template

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#372]
We need to be able to show two rows in the EN02 templates we use for Japanese. Perhaps the font size needs to be adjusted a bit? Not sure, since it look like the left column is displaying just fine…

![enabling 2](https://cloud.githubusercontent.com/assets/7586260/8059867/0c06fb6c-0e77-11e5-94a4-bc89f055e878.png)

**Comment by proti9** [comment]
It would be checked when the font-size adjustment is applied.

**Comment by proti9** [comment]
It is updated. Please check it again.

**Comment by sdub** [comment]
Looks good, thank you!
