### ISSUE TITLE
WarmUp_03 - ja_01_05_10_01 - Japanese - Warm-Up3 template

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#373]
Since we are showing both romaji and kanji, we would like to be able to control the wrapping in the columns. Please give us the ability to use break tags as well as bold and italics in the TL column.Thanks!
 
![wu3_linebreaks](https://cloud.githubusercontent.com/assets/7586260/8060149/959d4a6a-0e78-11e5-98a4-826312b49698.png)

**Comment by proti9** [comment]
It is updated. Republishing the xml file would resolve the issue.
