### ISSUE TITLE
Enabling_32 - au_01_03_06_03 - LetterScramble - Arabic text direction issue

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#374]
Scrambled letters in Arabic are running LTR, not RTL as they should - template should also be right-aligned for RTL

![letterscrambleltr](https://cloud.githubusercontent.com/assets/7586260/8135618/728e1b0e-10ed-11e5-8147-4f3b9560b74c.png)

**Comment by proti9** [comment]
Interface design for RTL should be needed. And, it would be updated with the lower character part issue.

**Comment by proti9** [comment]
The update will be processed by applying this design and by checking other issues.

![enabling_32_rtl_temp](https://cloud.githubusercontent.com/assets/7441476/8189899/26a163b6-1414-11e5-8840-ee84f55382b7.jpg)

**Comment by sdub** [comment]
This design looks great, please implement in Staging....thank you!

**Comment by sdub** [comment]
Unfortunately, the scrambled letters in Arabic are still running LTR, not in  RTL as they should
![letterscrambleltr](https://cloud.githubusercontent.com/assets/7586260/8629416/f9877870-270f-11e5-888a-a7b454ba48ff.png)

**Comment by proti9** [comment]
It is updated. Please check it again.

**Comment by sdub** [comment]
Text direction is great now, thank you!
