### ISSUE TITLE
HS Enabling_07 - au_01_02_03_09

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#378]
The Arabic script should be right-aligned
![en7_ltr](https://cloud.githubusercontent.com/assets/7586260/8140763/81e86e76-1113-11e5-990c-6c68cc22f3f2.png)

**Comment by proti9** [comment]
It is updated. Please take a look again.

**Comment by sdub** [comment]
Looks good but the Arabic writing is very small, please increase in size by at least  two font sizes.

**Comment by proti9** [comment]
Font size is adjusted to 18px. Please check the activity again.

**Comment by sdub** [comment]
Thank you!
