### ISSUE TITLE
Enabling_07 - ja_01_03_06_06 - breaks in TL field

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#379]
As we would like to show both TL & romaji in the TL field, so we would like break tags to work in order to show the content on a new line.

![en7_breaks](https://cloud.githubusercontent.com/assets/7586260/8295564/c56c790a-18fa-11e5-9547-3425173ba9cc.png)

**Comment by botrosyoussef** [comment]
I think this should be achieved on the content side, by adding "<br>" after the Japanese text.

**Comment by botrosyoussef** [comment]
OLOG was updated for Japanese Language, which will enable the HTML code to show in the activity. Please re-publish and test in staging.

**Comment by sdub** [comment]
Seems to be working, thank you!
