### ISSUE TITLE
HS Enabling_08 - au_01_03_06_08 - Arabic text issue

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#380]
Script looks good in generator but develops two issues when exported to XML & viewed in Staging.
1) Text in blank field runs LTR instead of RTL
2) End of TL sentence is switched to show before the beginning of the sentence in TL box (see question mark placement)
![en8_script](https://cloud.githubusercontent.com/assets/7586260/8312841/eb3a2a30-1993-11e5-8def-6cb72b4f006f.png)

**Comment by proti9** [comment]
Give your comments for the below items to be applied. 

Play button - horizontally flipped and right aligned
RTL text sentences - right aligned

Then these would be also considered for the update.

**Comment by sdub** [comment]
Yes, please update the alignment and button direction as well. Thank you for checking!

**Comment by proti9** [comment]
Here would be a screen mockup.

![enabling_08_mockup_yemeni_v4](https://cloud.githubusercontent.com/assets/7441476/8583323/9278a30a-2581-11e5-9bf3-d85e9e3456b4.jpg)

**Comment by proti9** [comment]
The template is updated. In addition, the XML generator side for Yemeni is updated to show RTL language properly. Please re-publish tasks having activities using this template and add xml files into staging. Then the update will be reflected in staging.

**Comment by sdub** [comment]
This looks good but the Arabic writing is very small. Please increase in size by at least two font sizes.

**Comment by proti9** [comment]
Font size is adjusted to 18px for text areas showing Arabic. Please check the activity again.

**Comment by sdub** [comment]
Thank you!
