### ISSUE TITLE
Enabling_02 - ja_01_03_06_03 - Japanese - text overflowing

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#381]
Set 5 .
FB for car - text runs over text box even with scroll bars appearing

![en2_txtoverflow](https://cloud.githubusercontent.com/assets/7586260/8368141/89e9ef12-1b5b-11e5-93bc-b158c717da37.png)

**Comment by proti9** [comment]
It is updated. Please check it again.

**Comment by sdub** [comment]
Looks great! Thank you.
