### ISSUE TITLE
HS Evaluation_02 - au_01_03_06_10 - Arabic text display issues

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#382]
Arabic text alignment and display issues, but only in right-hand column in each set.
Left-hand column appears to be fine throughout.

![evaluation2_au_01_03_06](https://cloud.githubusercontent.com/assets/7586260/8379158/fc5bc3c8-1bd2-11e5-91d4-c297cd471e77.JPG)

![evaluation2_x2_au_01_03_06](https://cloud.githubusercontent.com/assets/7586260/8379161/fda77362-1bd2-11e5-82f8-fed1480b0aaa.JPG)

**Comment by proti9** [comment]
It is updated. Please check it again.

**Comment by sdub** [comment]
Alignment is OK now, but the font in the drop-down appears as different type than rest of sentence, please update,

**Comment by sdub** [comment]
Issue with different  font in drop-down persists, please advise.

**Comment by sdub** [comment]
Also, image does not display until after clicking Play button. does template  need both png and mp4?

**Comment by sdub** [comment]
Issue with different font in drop-down persists, please advise. 
Additionally, the Arabic writing is very small. Please increase in size by at least two font sizes.

**Comment by proti9** [comment]
It is updated. Please try it again.

**Comment by sdub** [comment]
Thank you!
