### ISSUE TITLE
Enabling_10 - ja_01_03_05_03 - Bold tags in drop-down menu

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#383]
please enable bold tags for the TL drop-down menu...Thank you!

**Comment by proti9** [comment]
The area is originally used for a plain English text without tags. And, the template accepts some cases using a plain text without tags so far. The template will be checked whether it could meet this needs or not.

**Comment by botrosyoussef** [comment]
OLOG has been updated for Enabling_10 to allow for bold tags. Please re-publish, then changes will be reflected on staging.

**Comment by sdub** [comment]
Thank you!
