### ISSUE TITLE
Enabling_09 - ja_01_02_03_06 - breaks, bold text in TL field

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#384]
Please add bold tags and break tag functionality to the TL field if possible.

**Comment by botrosyoussef** [comment]
Bold tags will effect the entire content including EN, is that OK?
not sure what is break tag.

**Comment by botrosyoussef** [comment]
Functionality was added to staging, will be added to GITHUB upon closing.

**Comment by sdub** [comment]
Looks good, thank you!
