### ISSUE TITLE
HS Language List scrolling issue

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#385]
When trying to select the last language on this list (Yemeni), the list scrolls up instead of letting you click and proceed
 ![listscroll](https://cloud.githubusercontent.com/assets/7586260/8629039/89609002-270c-11e5-82b2-2904ea85373f.png)

**Comment by proti9** [comment]
Please try to click "U-Z" and "Launch Course Now" for Yemeni as shown in the below screenshot. It would let you click it and proceed.

![image](https://cloud.githubusercontent.com/assets/7441476/8658868/5b381b2c-295b-11e5-9a51-dfa623ac085a.png)

**Comment by sdub** [comment]
This is always a possibility, but perhaps not necessarily something our users will do, I think we will have to solve this issue eventually.

**Comment by sdub** [comment]
Issue persists.

**Comment by proti9** [comment]
It is updated. Please try again.

**Comment by sdub** [comment]
Works nicely now! Thank you!
