### ISSUE TITLE
Enabling_08 - au_01_03_06_08 - Arabic text display issues

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#386]
Step 8, Enabling 8:

alignment is incorrect 1) in question box; 2) in letter box; 3) in answer box. 

![enabling8_alignments](https://cloud.githubusercontent.com/assets/7586260/8629128/7b43fa30-270d-11e5-9876-8caa95af181a.JPG)

**Comment by proti9** [comment]
The template is updated. In addition, the XML generator side for Yemeni is updated to show RTL language properly. Please re-publish tasks having activities using this template and add xml files into staging. Then the update will be reflected in staging.

**Comment by sdub** [comment]
Seems to work well now, thank you!
