### ISSUE TITLE
Enabling_04 - au_01_06_11_03 - Arabic text display issues, missing keyboard

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#387]
Yemeni Task 11 Step 3 Enabling 4:

1) needs Arabic keyboard

2) reverses text direction from RTL (Enabling4_1.JPG)  to LTR when the missing letter is the first letter of the phrase and an incorrect letter is selected (Enabling4_2.JPG); reverts to RTL after second time letter is selected (Enabling4_3.JPG) : eg, “bright color” (item 15 in Generator, 5th item auto-displayed)

![enabling4_1](https://cloud.githubusercontent.com/assets/7586260/8629187/efb5902c-270d-11e5-8fc9-e5f687547dcb.JPG)

![enabling4_2](https://cloud.githubusercontent.com/assets/7586260/8629188/f023711e-270d-11e5-95ac-5de24eb32b55.JPG)

![enabling4_3](https://cloud.githubusercontent.com/assets/7586260/8629189/f5afad14-270d-11e5-9544-3e78220846e7.JPG)

**Comment by proti9** [comment]
It is updated to show Yemeni characters in contents as characters in the keyboard set. Please try again how it shows.

**Comment by sdub** [comment]
Getting there! Two things I notice that should be addressed:
1) The font is being pulled apart in this template so the Arabic text is not connecting as it should.
2) Also the letter sticks to the right of the white box once it is place, please update if possible so that it is in the middle.

![en4_font](https://cloud.githubusercontent.com/assets/7586260/10021244/05714276-60fc-11e5-94f9-cce018c81b28.png)

**Comment by proti9** [comment]
It is updated letters to be connected and to be in the middle. Please try again.

**Comment by sdub** [comment]
Seems to work well now, though the Arabic font used in the letter pool is a different one than is used in the word box above. Please update to the same font in order to ensure a professional look and feel.

**Comment by proti9** [comment]
It is updated. Please try it again.

**Comment by sdub** [comment]
Thank you!
