### ISSUE TITLE
Mil_01 - au_02_01_01_01 - Arabic text display issue

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#388]
Mil 01 Template - Arabic font is not right-aligned and also too small
![mil01_fonts](https://cloud.githubusercontent.com/assets/7586260/8678211/2d977912-2a08-11e5-8e86-8c4b6fd38711.png)

**Comment by proti9** [comment]
It is updated. Please check it again.

**Comment by sdub** [comment]
It is correctly aligned now. Separate issue opened regarding font size.
