### ISSUE TITLE
HS Enabling_12 - au_01_06_11_07 - display issues

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#389]
The images do not display until after the play button is clicked.
Except for the last image in some sets, which does display automatically.

![enabling12_missing_images](https://cloud.githubusercontent.com/assets/7586260/8686610/b5f7ce68-2a3c-11e5-9a33-2d658614bf9f.JPG)

**Comment by proti9** [comment]
Having ogv files would resolve this issue. Pease check it again.
