### ISSUE TITLE
Enabling_05 - ja_01_02_04_04 - Enable tgas in TL column

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#390]
Please enable tags in TL column (break and bold)

**Comment by proti9** [comment]
Enabling_05 is used on ja_01_03_05_02 for example. And, it supports tags on left side TL items. 
Enabling_09 is used for ja_01_02_04_04. And, it supports tags on draggable items.
Please check it again and let me know what you want to be.

**Comment by sdub** [comment]
Not sure anymore, cannot find coordinator comment. Closing for now.  : (
