### ISSUE TITLE
HS Mil_01 - au_02_01_01_01 - Arabic Font display

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#400]
Please increase size of Arabic font by two font sizes both beneath the avatar and in the list on the left. Both are quite hard to read now.
![mil_s1_fontsize](https://cloud.githubusercontent.com/assets/7586260/10803004/478b9308-7d7d-11e5-9980-030665bfae33.png)

**Comment by proti9** [comment]
Font sizes are adjusted for below items.

List item: 18px
Beneath the avatar: 24px

Please check the activity again.

**Comment by sdub** [comment]
Looks good now, thank you! I think 18 pts will be what we'll need for many of the SNS templates as well.

**Comment by sdub** [comment]
in all Mil step 1, text box on the right, Translation tab, Arabic is slightly too large, lines overlap 

![au_mil__fontoverlap_mod9t5](https://cloud.githubusercontent.com/assets/7586260/11277886/5a16bc60-8e9d-11e5-85c5-1d6092365bba.JPG)

**Comment by proti9** [comment]
It is updated. Please try again.

**Comment by sdub** [comment]
Thank you!
