### ISSUE TITLE
HS Mil_02 - au_02_01_01_02 - Feedback Font display

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#401]
Feedback is quite small, please increase size by at least two points

![mil_s2_fontsize](https://cloud.githubusercontent.com/assets/7586260/10803144/01cfaa2e-7d7e-11e5-9dc4-1528ad4d5d1f.png)

**Comment by proti9** [comment]
Font size is adjusted to 16px. Please check the activity again.

**Comment by sdub** [comment]
This should work! Thank you.
