### ISSUE TITLE
HS Enabling_09 - au_01_03_05_06 - Arabic text issues

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#402]
Need to right align font and make sure Arabic script does not separate in the FB.

![au_en9_alignment_connect](https://cloud.githubusercontent.com/assets/7586260/10888348/92ef9abc-8140-11e5-8bb5-7a5d57aaef4b.JPG)

**Comment by proti9** [comment]
It is updated. Please try it again.

**Comment by sdub** [comment]
Works well now, thank you!
