### ISSUE TITLE
HS Capstone_01 - au_01_09_18_07 - Arabic text issues

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#403]
Arabic scripts in Capstone 1 template are not connecting
![cap1_connect](https://cloud.githubusercontent.com/assets/7586260/10916843/5e9986b0-8212-11e5-960c-e256f269c948.JPG)

**Comment by proti9** [comment]
It is updated. Please try it again.

**Comment by sdub** [comment]
Looks good, thank you!

**Comment by sdub** [comment]
Unfortunately, somehow the Arabic font in the military Capstone activities is back to not connecting. Please check all capstone templates

![capstones_font](https://cloud.githubusercontent.com/assets/7586260/11478290/ef4c2ba2-9740-11e5-8f31-72535498f066.png)

**Comment by proti9** [comment]
It is updated. Please try it again.

**Comment by sdub** [comment]
Looks good, thank you!
