### ISSUE TITLE
HS Enabling_31 - WordMissingLetter - au_01_01_02_06 - Arabic font display issues

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#405]
In Yemeni Task 2, Step 6 (Word Missing Letter) the Arabic font is not connecting properly.
![wml_letter spacing t2 s6](https://cloud.githubusercontent.com/assets/7586260/11040281/4eff1c26-86c0-11e5-82e2-9e68cd240156.PNG)

**Comment by proti9** [comment]
It is updated. Please try it again.

**Comment by sdub** [comment]
Thank you!
