### ISSUE TITLE
HS Enabling_01 - au_01_07_13_03 - Arabic font alignment

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#406]
In EN1, Layer Two,t he feedback box automatically includes text from Generator field “Target Language Phrase”.
This text needs to be aligned to the right margin for Yemeni. Generator input is already selected “Set Dir” to the right.

![en1_align](https://cloud.githubusercontent.com/assets/7586260/11041162/f917a828-86c4-11e5-8b4b-cac5754d522d.JPG)

**Comment by proti9** [comment]
It is updated. Please try it again.

**Comment by sdub** [comment]
Thank you!
