### ISSUE TITLE
HS Capstone_05 - au_02_04_06_05 - Arabic font alignment and appearance

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#408]
Arabic font on left side of screen needs to 1) have connecting letters   2) be right-aligned 3) be larger 

![capstone5_font](https://cloud.githubusercontent.com/assets/7586260/11478530/73e99ede-9742-11e5-985d-2b679089c790.png)

**Comment by proti9** [comment]
It is updated. Please try it again.

**Comment by sdub** [comment]
Looks good, thank you!
