### ISSUE TITLE
HS Mil_02 - au_02_08_03_02 - Gray bar appearing in template

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#409]
An odd gray bar has started appearing in the Mil Step 2 template
![mils2_bar](https://cloud.githubusercontent.com/assets/7586260/11480982/713b93b0-974f-11e5-9652-f631c209814f.png)

**Comment by proti9** [comment]
In my side, it looks OK as shown in the below. At this moment, it will stay as it is.

![au_02_08_03_02_151130](https://cloud.githubusercontent.com/assets/7441476/11482399/6dff801e-9757-11e5-9085-eb84e885e866.jpg)
